markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

#gauges_id: 503c5af6613f5d0f19000027
#google_analytics_id: UA-50755011-1

ctx_path: http://jeesite.github.io/jeesite.com/
repository: https://github.com/jeesite/jeesite.com
help_url: http://thinkgem.iteye.com/category/267394
blog_url: http://thinkgem.iteye.com

collections:
  docs:
    output: true
